# Generated by Django 5.0.7 on 2024-08-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
