# Generated by Django 5.0.7 on 2024-08-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
