# Generated by Django 5.0.7 on 2024-08-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_status_category_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='gender',
            field=models.CharField(choices=[('MEN', 'male'), ('FEMALE', 'female'), ('UNISEXUAL', 'unisexual')], default='UNISEXUAL'),
        ),
    ]
