# Generated by Django 5.0.7 on 2024-08-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_varient_image_1_varient_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='varient',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
