# Generated by Django 5.0.7 on 2024-08-19 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_varient_image_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varient',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.products'),
        ),
    ]
