# Generated by Django 5.0.7 on 2024-08-31 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_brandoffer_productoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandoffer',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.brand'),
        ),
        migrations.AlterField(
            model_name='brandoffer',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
