# Generated by Django 5.0.7 on 2024-08-31 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_brandoffer_brand_alter_brandoffer_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandoffer',
            old_name='discount',
            new_name='discount_percentage',
        ),
    ]
