# Generated by Django 5.0.7 on 2024-08-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(choices=[('cash on delivery', 'cash on delivery'), ('online payment', 'online payment')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
