# Generated by Django 5.0.7 on 2024-08-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orders_address_alter_orderaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
