# Generated by Django 5.0.7 on 2024-09-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_wallet_user_delete_transaction_delete_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('return_request', 'return_request')], max_length=20),
        ),
    ]
