# Generated by Django 5.0.7 on 2024-09-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orders_coupon_alter_orders_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='discounted_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
