# Generated by Django 5.0.7 on 2024-09-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orders_discounted_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='discounted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
