# Generated by Django 5.0.6 on 2024-08-05 15:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'male'), ('U', 'male')], default='U', max_length=1)),
                ('colour', models.CharField(choices=[('B', 'black'), ('W', 'white'), ('S', 'silver'), ('B', 'blue'), ('G', 'green')], max_length=1)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('discription', models.TextField()),
                ('price', models.IntegerField()),
                ('quatity', models.IntegerField()),
                ('status', models.BooleanField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='login.category')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='login.brand')),
            ],
        ),
    ]
