# Generated by Django 5.0.7 on 2024-08-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='State',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
