# Generated by Django 5.0.7 on 2024-08-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('MEN', 'male'), ('FEMALE', 'female'), ('Not mention', 'null')], default='Not mention'),
        ),
    ]
