# Generated by Django 5.0.7 on 2024-09-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('MEN', 'male'), ('FEMALE', 'female'), ('Not mention', 'null')], default='Not mention', max_length=20),
        ),
    ]
