# Generated by Django 5.0.7 on 2024-08-19 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0007_alter_varient_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='p_id',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='varient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.varient'),
            preserve_default=False,
        ),
    ]
